### ISSUE TITLE
无法添加vhost

### ISSUE THREAD

**Issue by huhu2207** [lj2007331/lnmp#100]
各位好，目前情况是这样的，如果我执行“./vhost.sh”后，输出是这样的：

```
root@vultr:~/work/lnmp# ./vhost.sh

#######################################################################
#       OneinStack for CentOS/RadHat 5+ Debian 6+ and Ubuntu 12+                             #
#       For more information please visit http://oneinstack.com                                          #
#######################################################################
root@vultr:~/work/lnmp#

```

也就是只有一个标题，其他什么都没有。
说下环境，我这是Vultr的VPS，系统是Debian 8 Jessie x64，更新到最新版，lnmp版本是最新的。

求各位大神指教，先谢谢了！

Jackson

**Comment by lj2007331** [comment]
额 安装 nginx 了吗？

**Comment by huhu2207** [comment]
@lj2007331 确定是安装成功了的，您可以访问hu-studio.com试试。

**Comment by huhu2207** [comment]
@lj2007331 

[install.txt](https://github.com/lj2007331/lnmp/files/50374/install.txt)

发个install.log您看下，好像并没有啥问题啊。因为github不给上传log后缀名，所以给我改成txt了。

**Comment by huhu2207** [comment]
呃没有诶

**Comment by lj2007331** [comment]
安装php7 ，apache编译的模块是libphp7.so 不是libphp5.so ，已经解决，谢谢你的case

**Comment by huhu2207** [comment]
好的，辛苦了
