### ISSUE TITLE
Virtual Host got 502 error

### ISSUE THREAD

**Issue by ceceps** [lj2007331/lnmp#103]
I had install successfull nginx,mysql, and php 5.6 , In main domain is working, but using virtual host I have  502 bad gateway. 

I setup like this config 
http://pastebin.com/Ap8sJc1C

add setup on other.conf 
http://pastebin.com/hmeP014m

**Comment by lj2007331** [comment]
You must `fastcgi_pass 127.0.0.1:9000;` change to `fastcgi_pass unix:/dev/shm/php-cgi.sock;`
