### ISSUE TITLE
vhost.sh有问题

### ISSUE THREAD

**Issue by njzhenghao** [lj2007331/lnmp#108]
新建主机的时候，比如让www.xxx.com跳转至主站xxx.com，https下，不能跳转，www.xx.com的状态为200，不是301，要添加到最后一个server配置里面才能生效，截个图

![](http://ww1.sinaimg.cn/large/6a8b44dbgw1f23kil90zpj20dj037gmg.jpg)

**Comment by njzhenghao** [comment]
shell不熟，没法修改。。。。。。

**Comment by lj2007331** [comment]
$server_name 改成绑定域名试试
