### ISSUE TITLE
Breaks XRDP

### ISSUE THREAD

**Issue by Darksleep** [lj2007331/lnmp#110]
XRDP works fine without this but then when installed xrdp dose not like to be used it wont reboot restart start nothing no errors just wont play nice

**Comment by lj2007331** [comment]
You must open the XRDP iptables port, default iptables file:/etc/iptables.up.rules

**Comment by Darksleep** [comment]
how would i do that as i not really played with iptables

**Comment by lj2007331** [comment]
Do you know xrdp which ports need to open it?
or:
close iptables:
rm -rf /etc/network/if-pre-up.d/iptables
reboot
