### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by zdraveski** [lj2007331/lnmp#111]
Can you please consider to implement Mod_Pagespeed for Apache https://github.com/pagespeed/mod_pagespeed 

And Automatic PageSpeed optimization module for Nginx  https://github.com/pagespeed/ngx_pagespeed

Thanks for your time
Best Regards

**Comment by lj2007331** [comment]
This module has been added long ago, but user feedback is unstable, it will cause the server to crash and cpu 100%
