### ISSUE TITLE
老版本的ImageMagic怎么升级？或者说里面的小部件怎么自主升级

### ISSUE THREAD

**Issue by petcat** [lj2007331/lnmp#113]
upgrade.sh 只包含了 php, mysql, phpmyadmin, 之类的升级，然而这次ImageMagic爆出漏洞，应该怎么方便升级。
其实可不可以这样，把 /include/ImageMagic.sh 之类的.sh 都做成能安装升级的？

**Comment by lj2007331** [comment]
参考：https://blog.linuxeye.com/446.html
