### ISSUE TITLE
ImageMagick_version=6.9.3-10 无法下载到.

### ISSUE THREAD

**Issue by wxYang** [lj2007331/lnmp#114]
默认使用的是 http://downloads.sourceforge.net/project/imagemagick/old-sources/6.x/6.8/ImageMagick-$ImageMagick_version.tar.gz 无法下载.
查看了下,目录有所改变.
换成下面链接可以用:
http://downloads.sourceforge.net/project/imagemagick/**6.9.3-sources**/ImageMagick-6.9.3-10.tar.gz

**Comment by petcat** [comment]
我换成官网的
不明白为何这里挺保守的，都不是最高版本，PHP扩展也不是最高的，而且也不明白为何用 SF的源。
是兼容的问题？

**Comment by lj2007331** [comment]
抱歉，已经提交更新
有新版本可能会有兼容性问题，

**Comment by lj2007331** [comment]
已更新到最新
