### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by tanvirredwan** [lj2007331/lnmp#124]
you dont't need to use python to grab the ip address. just install ntp or other package to ping google.
because if taobao down, your software will be unable to update the host file.
as a result, installing this soft on vps or server useless.
client will get package error.
max cheap unmanaged server comes with raw. if there python not installed , user will get /env error
there's lot of people, they don't know a single piece of command or 2 line code
make your script bulletproof

**Comment by lj2007331** [comment]
Python comes preinstalled on most Linux distributions
I just updated README.md
python script i get a timeout
