### ISSUE TITLE
想问一下，nginx在做反向代理是，有多个upstream，如何保持session一致的问题

### ISSUE THREAD

**Issue by Jerry-goodboy** [lj2007331/lnmp#137]
#### 比如我ajax的请求链接是 http://api.backend.com/books/，我前端传的参数是 bookname=snow，但是在nginx做转发的时候，需要带上几个验证参数，比如是 sign=cdsdxxdsf900sdf&type=web，这种的前端浏览器通过开发者工具也看不到的参数，这些静态的参数好办，可以rewrite，但是，接口那边又要求传一个字段，copyright=free，或者copyright=purchase，等这样的需要通过书名来判断的动态参数，并且不能在前端做判断，并且在不用PHP，node等后端脚本语言的前提下， nginx如何做到，根据我前端传的  bookname=snow ，来动态的决定copyright是free 还是 purchase，请问这种代码在nginx里怎么写？

@lj2007331 @rindeal @wedojava @421darren

**Comment by jackytang** [comment]
这个好像有很多办法，简单的有下面两种：
1. 安装插件，详见：https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng
2. 安装Tengine，已经集成了nginx-stick插件
复杂点的话，那就是session复制或者把session保存到数据库之类的方式了

**Comment by Jerry-goodboy** [comment]
@jackytang 
大神能给个nginx + PHP 相关的 session持久化问题的例子或者帖文么？我现在还是不太会弄，我再上一张我刚刚画的图来阐述一下我现在遇到的问题：
<img width="855" alt="2016-10-03 22 15 51" src="https://cloud.githubusercontent.com/assets/9030784/19040519/03552112-89b7-11e6-8abc-19e53bf849aa.png">

### 首先说一下我们现在用的服务器的组织构成，第一个放在前端的是nginx服务器，其最主要的功能就是反向代理和负载均衡，其内部不运行任何PHP代码。
- 反向代理目的为了ajax可以跨域调用API；
- 负载均衡目的是为了减轻服务器压力；

### 然后就是最关键的一点了，就是nginx转发过来的请求，无论其内部选用ip_hash也好还是其他的什么负载方式，现在就是在想，有什么好办法可以让nginx无论转发哪个URL请求，也无论是转到给哪个API server，都希望其所命中的 session 是正确的，举个例子：

- client 发一个 请求，地址是 http://backend.com/books/list （但是这个请求是有权限限制的，不同的用户返回的结果不一样，那么识别用户的标识就被存到session里了 ）；
- 接着nginx转发了这个请求给 API server 1，此时的API server 1不认识这个用户，于是就创建了一个session，并重新提供了登陆的链接返了回去；
- 然后用户登陆完成后，又重新发起了 http://backend.com/books/list 这个链接，但是nginx把这个链接转发到了API server 2 上，但是 API server 2 上 并没有这个请求的session，于是又让用户重新登陆；

### 这个过程就不对了，现在我遇到的就是这种情况，请问大神如何破？

**Comment by lj2007331** [comment]
可以把session放到memcached中。。

**Comment by Jerry-goodboy** [comment]
@lj2007331 其实我发现，我好像对session理解的还是不那么透彻，我回头好好恶补一下这块的知识吧，谢谢啦，大神

**Comment by lj2007331** [comment]
google 一大把。。

**Comment by jackytang** [comment]
http://openwares.net/linux/nginx-tomcat-memcached-session-share-cluster.html
