### ISSUE TITLE
how put ssl for first time?

### ISSUE THREAD

**Issue by johnfelipe** [lj2007331/lnmp#142]
I run your wonderful script without ssl, but i need put my own csr and godaddy crt, what process and step will do for that?

Tnks

**Comment by lj2007331** [comment]
Do you want to setup SSL under Nginx? [y/n]:     y
Replace self-signed SSL Certificate: /usr/local/nginx/conf/ssl/www.example.com.crt 
Replace SSL Private Key: /usr/local/nginx/conf/ssl/www.example.com.key
service nginx restart

**Comment by johnfelipe** [comment]
I have ssl from godaddy, what is exactly process i need migrate http://actividadesudea.upncis.co/ to https://actividadesudea.upncis.co/
Tnks

**Comment by johnfelipe** [comment]
pls help me about this

**Comment by lj2007331** [comment]
you can replace Server's default private key and self-signed certificate with yours.
replace file:
/usr/local/nginx/conf/ssl/www.example.com.crt 
/usr/local/nginx/conf/ssl/www.example.com.key
