### ISSUE TITLE
禁止访问二级域名不成功？

### ISSUE THREAD

**Issue by viponedream** [lj2007331/lnmp#146]
比如我的网站 a.com
子域名 static.a.com 绑定到目录  \uploads

假如我访问  a.com/uploads/a.php  则没法访问php文件，这是正常的。因为禁止了。
但是我访问  static.a.com/a.php 则可以访问。这样就不对了。相当于可以执行到里面的脚本了。
请问这种情况要怎么办？

**Comment by lj2007331** [comment]
/usr/local/nginx/conf/vhost/static.a.com.conf 把php相关段注销掉
