### ISSUE TITLE
阿里云内网那个下载链接 似乎有问题。

### ISSUE THREAD

**Issue by cos800** [lj2007331/lnmp#163]
--2017-03-06 10:52:23--  http://aliyun-oss.linuxeye.com/lnmp-full.tar.gz
正在解析主机 aliyun-oss.linuxeye.com (aliyun-oss.linuxeye.com)... 100.100.45.2
正在连接 aliyun-oss.linuxeye.com (aliyun-oss.linuxeye.com)|100.100.45.2|:80... 失败：连接超时。
重试中。

--2017-03-06 10:54:32--  (尝试次数： 2)  http://aliyun-oss.linuxeye.com/lnmp-full.tar.gz
正在连接 aliyun-oss.linuxeye.com (aliyun-oss.linuxeye.com)|100.100.45.2|:80... ^C

**Comment by lj2007331** [comment]
这个链接只能在阿里云经典网络才能下载。
