### ISSUE TITLE
MariaDB Download Failed.

### ISSUE THREAD

**Issue by chaiyot** [lj2007331/lnmp#166]
I've tried to install mariadb (10.1) on digitalocean's VPS but it failed both install from binary and source. Below are example of error messages.

--2017-05-14 15:25:17--  (try:12)  http://download.nus.edu.sg/mirror/mariadb//mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz
Connecting to download.nus.edu.sg (download.nus.edu.sg)|137.132.155.168|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 478636602 (456M), 478543579 (456M) remaining [application/octet-stream]
Saving to: ‘mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz’

        [ skipping 50K ]
    50K ,,,,,,,,,, ,,,,,,,,,, ,,,,,,,,,, ,,,,,,,,,, .........   0% 9.16M=0.001s

2017-05-14 15:25:17 (9.16 MB/s) - Connection closed at byte 101476. Retrying.

--2017-05-14 15:27:18--  https://downloads.mariadb.org/interstitial/mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz
Resolving downloads.mariadb.org (downloads.mariadb.org)... 173.203.201.148
Connecting to downloads.mariadb.org (downloads.mariadb.org)|173.203.201.148|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://downloads.mariadb.org/f/mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz?serve [following]
--2017-05-14 15:27:20--  https://downloads.mariadb.org/f/mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz?serve
Reusing existing connection to downloads.mariadb.org:443.
HTTP request sent, awaiting response... 302 FOUND
Location: http://download.nus.edu.sg/mirror/mariadb//mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz [following]
--2017-05-14 15:27:20--  http://download.nus.edu.sg/mirror/mariadb//mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz
Resolving download.nus.edu.sg (download.nus.edu.sg)... 137.132.155.168
Connecting to download.nus.edu.sg (download.nus.edu.sg)|137.132.155.168|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz download failed, Please contact the author!

**Comment by lj2007331** [comment]
You can Download maraidb before installation:
```
cd oneinstack/src
wget -c http://download.nus.edu.sg/mirror/mariadb/mariadb-10.1.22/bintar-linux-glibc_214-x86_64/mariadb-10.1.22-linux-glibc_214-x86_64.tar.gz
cd ..
./install.sh
```
