### ISSUE TITLE
LDAP support for php

### ISSUE THREAD

**Issue by khiloc** [lj2007331/lnmp#173]
Hello
First all
A very huge thanks for that wonderfull script that you made!!
please i would likle to ask if it is possible to add php ldap support?
using it for a wordpress project in which i run ldap authentication back to my active directory (usage for an internal server)
but seems to currently lack support for ldap...

**Comment by kmahyyg** [comment]
search tutorials on the web, they won't add it.

khiloc <notifications@github.com>于2017年6月28日周三 16:57写道：
