### ISSUE TITLE
secure_mysql_installation command?

### ISSUE THREAD

**Issue by johnfelipe** [lj2007331/lnmp#177]
What does "secure_mysql_installation" do exactly?: The "secure_mysql_installation" command secures your Database server. When running a production level grid (where the general public can create accounts and login to the grid), it is always a wise idea to run this command. This helps prevent hackers from hacking into the root useraccount on the server, prevents flooding of database tables and creation of fake database tables and information, blocks the creation of anonymous users, and closes some very bad back doors to the server. Upon doing this command just like above you will have to edit the /etc/mysql/my.cnf file and changed the IP address that the server is bound to, so it will bind to the external IP of the machine the database server is on. After you will need to restart the Database server for changes to take effect.

**Comment by johnfelipe** [comment]
anyone?

**Comment by lj2007331** [comment]
Installation has been executed
