### ISSUE TITLE
为什么教程里推荐默认选择安装 redis 和 memcached

### ISSUE THREAD

**Issue by h2y** [lj2007331/lnmp#187]
我认为，这两个组件并不算是安装好了就开箱即用的类型，需要在已有系统上安装相应的插件才会有提速的效果。所以教程中应该默认不安装，或者做出相关说明。

或者是我理解错了？这两个组件只要选择安装，就可以直接实现提速效果？

**Comment by fslove** [comment]
redis memcached 都是内存CPU大户，如果没有信仰或产品支持，个人建议还是不安装吧
