### ISSUE TITLE
这空间吃的有点大

### ISSUE THREAD

**Issue by fslove** [lj2007331/lnmp#188]
mysql+php7+nginx 其他都不选
![image](https://user-images.githubusercontent.com/10248063/32373337-5f52fc5e-c0cb-11e7-85e2-9df7744b289b.png)

**Comment by fslove** [comment]
重装两遍，以前沒在意過空间，这在意起来都有点怀疑人生了。

**Comment by fslove** [comment]
mariadb 10.x不能选择源码编译，很多错误，先是mysql.server这个文件不存在，后来又出来个，放弃了手动编译了。
mariadb 如果选择bin安装，会增加1~2g使用空间。

**Comment by fslove** [comment]
个人建议编译完后来个 生产环境/开发环境 清理选项。

**Comment by itviewer** [comment]
现在安装后还不能清理编译的临时文件吗

**Comment by lj2007331** [comment]
已加
