### ISSUE TITLE
Error while installing Memcached

### ISSUE THREAD

**Issue by fabiospampinato** [lj2007331/lnmp#190]
During the `install.sh` process, I decided that I wanted to install Memcached, and I see the `memcached` service got installed, but the `memcache` (without the **d**) extension is loaded in PHP. 

Then I tried to install the PHP extension via `addons.sh`, but I got this error:

```
checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located
make: *** No targets specified and no makefile found.  Stop.
~/lnmp/src ~/lnmp
PHP memcached module install failed, Please contact the author! 
```

How do I fix this?

**Comment by fabiospampinato** [comment]
An `apt-get install libmemcached-dev` fixed it, but I guess there shouldn't be the need to execute it manually.

**Comment by lj2007331** [comment]
fixed
