### ISSUE TITLE
Give user rights to upload files via SSH

### ISSUE THREAD

**Issue by beeyev** [lj2007331/lnmp#196]
I don't use FTP at all, so what rights shell i give to the user to get ability to upload files ?

**Comment by lj2007331** [comment]
You can use the SSH account to upload the file. 
Web site root permissions to follow:
file 644, folder 755, Permissions Users and groups www
If there is a file permissions problem, execute the following three commands:
chown  -R  www.www  /data/wwwroot/
find  /data/wwwroot/  -type  d  -exec  chmod  755  {}  \;
find  /data/wwwroot/  -type  f  -exec  chmod  644  {}  \;
