### ISSUE TITLE
This site can’t be reached blog.local’s server IP address could not be found. DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by Ostap34JS** [lj2007331/lnmp#197]
# I'm created new host, open and this error:
This site can’t be reached
blog.local’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
Please help me! thanks...

**Comment by lj2007331** [comment]
Where are the DNS records hosted?
Have you already added the DNS A record？
Your server Network accessible？
