### ISSUE TITLE
ss.sh on Ubuntu 16.04 install error. libsodium-dev is too old

### ISSUE THREAD

**Issue by ivan-zolotavin** [lj2007331/lnmp#201]
Install message error:
...ss_local-aead.o: In function `aead_cipher_decrypt'...
...aead.c:219: undefined reference...
...recipe for target 'ss-local' failed...

Need run:
`apt-get purge libsodium-dev`

Solution tested on Ubuntu 16.04 in file ss.sh change line:
`pkgList="curl wget unzip gcc swig automake make perl cpio git libmbedtls-dev libudns-dev libev-dev gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libc-ares-dev libsodium-dev"`
to
`pkgList="curl wget unzip gcc swig automake make perl cpio git libmbedtls-dev libudns-dev libev-dev gettext build-essential autoconf libtool libpcre3-dev asciidoc xmlto libc-ares-dev"`

**Comment by lj2007331** [comment]
Fixed https://github.com/lj2007331/lnmp/commit/2574d57431336d998b3bf90ef5bc39b16359f4b4
