### ISSUE TITLE
ubuntu 18.04 安装  jemalloc install failed

### ISSUE THREAD

**Issue by kaizhuQin** [lj2007331/lnmp#212]
[jemalloc-5.1.0.tar.bz2] found
~/lnmp ~/lnmp
~/lnmp/src/jemalloc-5.1.0 ~/lnmp/src ~/lnmp ~/lnmp
checking for xsltproc... false
checking for gcc... gcc
checking whether the C compiler works... no
~/lnmp/src ~/lnmp ~/lnmp
jemalloc install failed, Please contact the author!

**Comment by lj2007331** [comment]
C编译器没有安装，yum或者apt没有配置好吧
