### ISSUE TITLE
www and without www

### ISSUE THREAD

**Issue by johnfelipe** [lj2007331/lnmp#221]
Hi bro im very glad with your script, but i need to know what change i need to do for put:

https://conexionmas.com/ and
http://www.conexionmas.com/, this linked to https, that is possible?

Stay alert

**Comment by lj2007331** [comment]
/usr/local/nginx/conf/vhost/conexionmas.com.conf
if ($host != conexionmas.com) {  return 301 $scheme://conexionmas.com$request_uri;  }

**Comment by johnfelipe** [comment]
Hi bro is not working, i put in this file: 

/usr/local/nginx/conf/vhost/conexionmas.com.conf

  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
  **if ($host != conexionmas.com) { return 301 $scheme://conexionmas.com$request_uri; }**
  include /usr/local/nginx/conf/rewrite/wordpress.conf;

service nginx restart

and not working: http://www.conexionmas.com/, show this: 

![snag-0308](https://user-images.githubusercontent.com/428820/43749443-ba108338-99b9-11e8-8240-243a7a690021.png)

and i need view this:

![snag-0309](https://user-images.githubusercontent.com/428820/43749469-da598572-99b9-11e8-8cc7-252424c918f7.png)

**Comment by lj2007331** [comment]
/usr/local/nginx/conf/vhost/conexionmas.com.conf
server_name conexionmas.com www.conexionmas.com;
