### ISSUE TITLE
建议enable-fileinfo

### ISSUE THREAD

**Issue by xfight0** [lj2007331/lnmp#51]
建议安装php的configure中增加 --enable fileinfo。
因为pecl不能正确的安装fileinfo扩展了，会报错。只有通过安装的时候enable。

http://pecl.php.net/package/Fileinfo
> Fileinfo package has been superseded, but is still maintained for bugs and security fixes. Package has moved to channel php-src/ext/fileinfo, package in php sources.

一个小建议。感谢这个lnmp项目。

**Comment by lj2007331** [comment]
由于编译fileinfo需要大量内存，小内存机器通不过，所以disable了，可以手工更改functions/php-5.x.sh 添加 --enable-fileinfo
