### ISSUE TITLE
ubuntu 14.04 64X 安装ioncube 和 jmalloc 失败了。

### ISSUE THREAD

**Issue by uyson** [lj2007331/lnmp#68]
ubuntu 14.04 64X 安装ioncube 和 jmalloc 失败了。
运行环境 阿里云主机
还有imagemagick 也不能用。

**Comment by uyson** [comment]
php 5.5

**Comment by uyson** [comment]
博客不能留言了， 提示 No input file specified. 跳：https://blog.linuxeye.com/wp-comments-post.php

**Comment by lj2007331** [comment]
我在aliyun主机测试下，谢谢

**Comment by lj2007331** [comment]
@uyson 已经测试过了，确实有些有问题，是由于 imagick.so失败（这个问题是已知的，之前install.sh有过屏蔽处理，没处理对，已经更改）导致 ioncube 失败。jmalloc安装应该没有问题。谢谢！

**Comment by uyson** [comment]
多谢
