### ISSUE TITLE
针对CPU进行优化，我现在用的

### ISSUE THREAD

**Issue by netnova163** [lj2007331/lnmp#7]
tar zxvf libunwind-1.1.tar.gz
cd libunwind-1.1
CHOST="x86_64-pc-linux-gnu" \
CFLAGS=" -O3 -fPIC \
-fomit-frame-pointer \
-pipe \
-march=nocona \
-mfpmath=sse \
-m128bit-long-double \
-mmmx \
-msse \
-msse2 \
-maccumulate-outgoing-args \
-m64 \
-ftree-loop-linear \
-fprefetch-loop-arrays \
-freg-struct-return \
-fgcse-sm \
-fgcse-las \
-frename-registers \
-fforce-addr \
-fivopts \
-ftree-vectorize \
-ftracer \
-frename-registers \
-minline-all-stringops \
-fbranch-target-load-optimize2" \
CXXFLAGS="${CFLAGS}" \
./configure && make && make install

tar zxvf gperftools-2.1.tar.gz
cd gperftools-2.1
CHOST="x86_64-pc-linux-gnu" \
CFLAGS=" -O3 \
-fomit-frame-pointer \
-pipe \
-march=nocona \
-mfpmath=sse \
-m128bit-long-double \
-mmmx \
-msse \
-msse2 \
-maccumulate-outgoing-args \
-m64 \
-ftree-loop-linear \
-fprefetch-loop-arrays \
-freg-struct-return \
-fgcse-sm \
-fgcse-las \
-frename-registers \
-fforce-addr \
-fivopts \
-ftree-vectorize \
-ftracer \
-frename-registers \
-minline-all-stringops \
-fbranch-target-load-optimize2" \
CXXFLAGS="${CFLAGS}" \
./configure -disable-cpu-profiler \
-disable-heap-profiler \
-disable-heap-checker \
-disable-debugalloc \
-enable-minimal \
-enable-frame-pointers && make && make install

**Comment by lj2007331** [comment]
暂时不考虑
