### ISSUE TITLE
请问怎么优化服务器内存使用

### ISSUE THREAD

**Issue by gantoo** [lj2007331/lnmp#70]
我是1g内存 昨天装好lnmp后 使用率是百分之23

今天开传了个站点 点几个页面 内存占用百分之85了

不知道这样正常吗 请教怎么优化内存?

**Comment by lj2007331** [comment]
正常的。Linux内存管理机制：http://blog.linuxeye.com/362.html

**Comment by gantoo** [comment]
@lj2007331 thanks
