### ISSUE TITLE
PHP7 - dev 现在貌似还是没法跑 memcached 扩展吧？

### ISSUE THREAD

**Issue by kmvan** [lj2007331/lnmp#71]
服务倒是运行了，但 PHP7 认不出。

**Comment by lj2007331** [comment]
memcached 支持php7 的还没开发出来。。

**Comment by kmvan** [comment]
https://community.centminmod.com/threads/php-5-7-phpng-support-testing-for-centmin-mod-betas.892/#post-3979
这货他的 php 好像能跑 mem……

**Comment by lj2007331** [comment]
刚刚测试，memcached-2.2.0 在php5.7 下不能通过编译

**Comment by kmvan** [comment]
感谢确认。

**Comment by kmvan** [comment]
@lj2007331 https://github.com/php-memcached-dev/php-memcached 这个貌似可以通过！

**Comment by lj2007331** [comment]
试过，不行。。
