### ISSUE TITLE
建议提供xDebug的安装选项

### ISSUE THREAD

**Issue by wedojava** [lj2007331/lnmp#77]
没错,我用了这个一键包,系统是centos6.6,apache+nginx+php,我想要安装xDebug的话怎么办呢?编译安装又怕破坏原有的一些设置或者配置

**Comment by Santino-Wu** [comment]
1、 PECL

直接使用PECL安装：`# pecl install xdebug`

2、源码安装

｀# git clone git://github.com/xdebug/xdebug.git`


然后根据提示在php.ini中添加配置：`zend_extension=[xdebug.so的路径]`

参考：[http://xdebug.org/docs/install](http://xdebug.org/docs/install)

**Comment by lj2007331** [comment]
暂时不考虑加xdebug，选项太多，且用的人相对来说较少，可以通过@Santino-Wu 方法安装。

**Comment by wedojava** [comment]
和xDebug相比,是不是Zend Debug用的更多,我是在用PhpStorm时发现它只能用xDebug

**Comment by wedojava** [comment]
XDebug works with Eclipse and with Netbeans (and some other ide's).

ZendDebug doesn't work with Netbeans. ZendDebug is already configured in ZendServer.

还是自己安装xdebug吧
