### ISSUE TITLE
能否添加tomcat的支持.

### ISSUE THREAD

**Issue by lcyan** [lj2007331/lnmp#79]
# 建议添加tomcat的支持.  #
现在除了博客之类的跑在PHP的环境中,大部分应用还是需要java环境啊

**Comment by lj2007331** [comment]
下一步考虑添加吧

**Comment by binarx** [comment]
汗

**Comment by Santino-Wu** [comment]
该项目应该主要是针对LNMP环境的吧？支持太多会不会只是单纯增加复杂性呢？建议fork出来一个。

**Comment by lj2007331** [comment]
@Santino-Wu  已经fork出来了，地址：https://github.com/lj2007331/lempstack

**Comment by Santino-Wu** [comment]
@lj2007331 :+1:  * :nine:  :nine: :nine:

**Comment by lj2007331** [comment]
支持tomcat版本：地址：http://hnzxs.oicp.net/
