### ISSUE TITLE
mysql 的nosql 存储引擎HandlerSocket

### ISSUE THREAD

**Issue by netnova163** [lj2007331/lnmp#8]
cd packages/
tar zxvf ahiguti-HandlerSocket-Plugin-for-MySQL-1.1.0-2-g395fa55.tar.gz
cd ahiguti-HandlerSocket-Plugin-for-MySQL-395fa55
./autogen.sh
./configure --with-mysql-source=../${mysql_ver} --with-mysql-bindir=/usr/local/${mysql_ver}/bin --with-mysql-plugindir=/usr/local/${mysql_ver}/lib/plugin
make 
make install

percona mysql 自带此功能

**Comment by lj2007331** [comment]
建议安装percona，其余mysql版本暂时不安装
