### ISSUE TITLE
与Shadowsocks冲突！

### ISSUE THREAD

**Issue by Tanlet** [lj2007331/lnmp#80]
安装此脚本后，shadowsock就没法使用了！请问是否修改过Centos7的防火墙？

**Comment by lj2007331** [comment]
有设置防火墙的

**Comment by Tanlet** [comment]
但是我尝试关闭iptables和firewalld后，也是不通的

**Comment by lj2007331** [comment]
是不是有端口转发？

**Comment by Tanlet** [comment]
运维方面，我还是挺新手的！能大概告诉我应该怎样做？最好给个教程我。谢谢

**Comment by lj2007331** [comment]
搜索下 shadowsock iptables
