### ISSUE TITLE
安装LNMPA中途报错终止

### ISSUE THREAD

**Issue by kid740246048** [lj2007331/lnmp#82]
我尝试使用脚本安装LNMPA，结果每次都在中途报错终止，报错信息如下
系统坏境是Bandwagon，CentOS 7 x86_64

[ 48%] Building CXX object sql/CMakeFiles/sql.dir/sql_yacc.cc.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [sql/CMakeFiles/sql.dir/sql_yacc.cc.o] Error 4
make[1]: *** [sql/CMakeFiles/sql.dir/all] Error 2
make: *** [all] Error 2
MySQL install failed, Please contact the author!
Killed
[root@default lnmp]# functions/mysql-5.6.sh: line 182: /usr/local/mysql/scripts/mysql_install_db: No such file or directory
/etc/init.d/mysqld: line 256: my_print_defaults: command not found
/etc/init.d/mysqld: line 276: cd: /usr/local/mysql: No such file or directory
Starting MySQL ERROR! Couldn't find MySQL server (/usr/local/mysql/bin/mysqld_safe)
functions/mysql-5.6.sh: line 190: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 191: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 192: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 193: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 194: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 195: /usr/local/mysql/bin/mysql: No such file or directory
functions/mysql-5.6.sh: line 196: /usr/local/mysql/bin/mysql: No such file or directory
/etc/init.d/mysqld: line 256: my_print_defaults: command not found
ERROR! MySQL server PID file could not be found!

**Comment by lj2007331** [comment]
内存多大？/var/log/messages 可以给我下

**Comment by kid740246048** [comment]
内存是128M的，/var/log/下没有名为messages的文件

[root@default ~]# cd /var/log/
[root@default log]# ls
btmp  dmesg  dmesg.old  journal  lastlog  sa  tallylog  wtmp  yum.log

**Comment by lj2007331** [comment]
out of memory ，应该是内存太小。机器内存这么小还安装lnmpa ？

**Comment by kid740246048** [comment]
然而安装nginx，Apache，php都是正常的，就是安装MySQL时出了问题，而且错误信息中也指向了mysql_install-5.6.sh

**Comment by lj2007331** [comment]
内存太小，编译mysql很消耗内存，建议安装mariadb，不需要编译，就算安装成功，但是之后跑网站，也可能导致某些服务被系统kill掉。建议还是直接lnmp

**Comment by kid740246048** [comment]
已经从yum源安装了MySQL，现在跑起来还有30~40M内存空闲，先看着用吧，不行再想办法
