### ISSUE TITLE
通过vagrant安装的Linux,映射文件夹PHP无法被解析

### ISSUE THREAD

**Issue by wedojava** [lj2007331/lnmp#83]
系统:CentOS6.6
环境:Nginx+Apache+PHP+MySQL
虚拟软件:virtualBox
问题:
隐射了虚拟机文件夹`/home/wwwroot/demo_bhl`到宿主机文件夹`/home/user/vagrant_f/`,确定这些文件夹确实存在,并且隐射成功,本机`/etc/hosts`文件设置也没有问题,但是访问该位置时,总是显示错误说页面没有找到.

我觉得可能是权限问题吧,如果是文件夹的权限问题应该怎么办才能解决这个问题呢?

**Comment by lj2007331** [comment]
权限默认都是www

**Comment by wedojava** [comment]
现在的问题是,我用`./vhost.sh`新增,如果文件夹是和宿主主机映射的,那么该位置的网站是打不开的,何解?我估计但凡用vagrant搞起来的虚拟机,如果用此一键包都会遇到这个问题,还烦请作者解答解答吧,好歹指条路~

**Comment by wedojava** [comment]
搞定了,要修改解析PHP的引擎的配置文件,将`User  www`改为`User  vagrant`
 -  如果是lnmp,那么就修改php-fpm的配置文件www.conf(具体位置不详,我用的时lnmpa),将`user = www`改为`user = vagrant`
 -  如果是lnmpa,那么就修改Apache的配置文件`/usr/local/apache/conf/httpd.config`,将`User  www`改为`User  vagrant`

修改完毕需要将网站目录的所有者改一下:`chown -R vagrant 网站目录`

**Comment by lj2007331** [comment]
你可以安装前设置 options.conf ，run_user=vagrant
