### ISSUE TITLE
pcre download url error

### ISSUE THREAD

**Issue by xiaosong** [lj2007331/lnmp#85]
http://downloads.sourceforge.net/project/pcre/pcre/8.37/pcre-8.37.tar.gz

should be:

http://downloads.sourceforge.net/projects/pcre/pcre/8.37/pcre-8.37.tar.gz

**Comment by xiaosong** [comment]
貌似错了，现在又可以下载了

**Comment by lj2007331** [comment]
project是对的，带s的是错误的，最近sf不太稳定。。
