### ISSUE TITLE
安装选择Percona5.6会导致错误

### ISSUE THREAD

**Issue by satifanie** [lj2007331/lnmp#93]
如果选择了Percona5.6 会导致，安装失败：启动MySQL的日志会出现：

2015-08-18 10:38:31 19850 [ERROR] Can't find messagefile '/usr/share/mysql/errmsg.sys',

另外，后台登陆mysql会导致：

/usr/local/percona/bin/mysql -uroot -p 

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

似乎不是在这个目录

**Comment by lj2007331** [comment]
http://oneinstack.com/question/in-the-current-version-of-percona5-6-is-not-available/
