### ISSUE TITLE
关于Limit的设置

### ISSUE THREAD

**Issue by satifanie** [lj2007331/lnmp#94]
博客https://blog.linuxeye.com/427.html 说的，实测在Ubuntu14.04上也不生效，
需要指定特定的用户。

**Comment by lj2007331** [comment]
/etc/security/limits.d/ 里面没文件吗？

**Comment by satifanie** [comment]
![image](https://cloud.githubusercontent.com/assets/1272881/9541638/c0213734-4d9c-11e5-8619-7f6668a7d3d5.png)
情况是这样的。我也是无意中发现的。包括oschina.net的站长也遇到过问题

**Comment by satifanie** [comment]
如果是 * soft nproc 65535
* hard nproc 65535
* soft nofile 65535
* hard nofile 65535 
重启后
root@sfo:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7782
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7782
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
