### ISSUE TITLE
hhvm pcre 不支持UTF8 

### ISSUE THREAD

**Issue by uyson** [lj2007331/lnmp#95]
你好！， hhvm的preg_match 函数不支持，

错误提示： hhvm Compilation failed: this version of PCRE is compiled without UTF support at offset 0

**Comment by uyson** [comment]
系统 Centos 7 阿里云主机， 相关的issue: https://github.com/facebook/hhvm/issues/4300

**Comment by lj2007331** [comment]
hhvm 请慎用，兼容性问题。。
